<?php

declare(strict_types=1);

namespace App\Console\Commands;

use App\Models\SiteSetting;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\Http;

class TypesenseSaveKey extends Command
{
    protected $signature = 'typesense:save-key {keyId=1} {--admin : Save as admin key instead of search key}';

    protected $description = 'Fetch a Typesense key by ID and persist it into site_settings';

    public function handle(): int
    {
        $keyId = (int) $this->argument('keyId');
        $asAdmin = $this->option('admin');

        $config = config('typesense');
        $node = $config['nearest_node'] ?? $config['nodes'][0];
        $base = sprintf('%s://%s:%s', $node['protocol'], $node['host'], $node['port']);

        // Admin key: just persist the configured admin key (Typesense does not return admin key via API)
        if ($asAdmin) {
            $value = $config['api_key'] ?? null;
            if (! is_string($value) || $value === '') {
                $this->error('typesense.api_key is not set');
                return self::FAILURE;
            }
        } else {
            // Search key: create a new search-only key and persist its value
            $resp = Http::withHeaders([
                    'X-TYPESENSE-API-KEY' => $config['api_key'], // admin key expected here
                    'Content-Type' => 'application/json',
                ])
                ->timeout($config['connection_timeout_seconds'] ?? 2)
                ->post("{$base}/keys", [
                    'description' => 'Search-only key (generated by typesense:save-key)',
                    'actions' => ['documents:search'],
                    'collections' => [$config['collection']],
                    'expires_at' => 0,
                ]);

            if (! $resp->successful()) {
                $this->error('Failed to create search key: ' . $resp->body());
                return self::FAILURE;
            }

            $value = $resp->json('value');
            if (! is_string($value) || $value === '') {
                $this->error('Key value missing in create response');
                return self::FAILURE;
            }
        }

        $settings = SiteSetting::query()->firstOrNew([]);
        if ($asAdmin) {
            $settings->typesense_admin_key = $value;
        } else {
            $settings->typesense_search_key = $value;
        }
        $settings->save();

        $this->info(($asAdmin ? 'Admin' : 'Search') . " key saved to site_settings.");
        return self::SUCCESS;
    }
}
