export const componentInventory = {
  buttons: ['PrimaryButton', 'TextButton', 'IconCircleButton'],
  auth: [
    'AuthScreen',
    'AuthBlobBackground',
    'AvatarBadge',
    'RoundedInput',
    'PinBoxes',
    'PinDots',
    'OptionPill',
    'RecoveryCodeContent',
  ],
  onboarding: ['OnboardingBackground', 'OnboardingCard', 'PaginationDots'],
  ui: [
    'CircleIconButton',
    'Chip',
    'SearchBar',
    'ProductCard',
    'SeeAllAction',
    'CategoryCard',
    'SectionHeader',
    'PopularCard',
  ],
  overlays: [
    'PortalHost',
    'Portal',
    'ModalSheet',
    'Dialog',
    'AddCardSheet',
    'EditCardSheet',
    'DeleteAccountDialog',
    'MaximumAttemptsDialog',
  ],
} as const;
