export const screenSequence = [
  { id: '001', route: '/', name: 'Welcome' },
  { id: '002', route: '/auth/register', name: 'Create Account' },
  { id: '003', route: '/auth/login', name: 'Login' },
  { id: '004', route: '/auth/password', name: 'Password' },
  { id: '005', route: '/auth/password', name: 'Password Typing (State)' },
  { id: '006', route: '/auth/password', name: 'Password Wrong (State)' },
  { id: '007', route: '/auth/forgot', name: 'Password Recovery' },
  { id: '008', route: '/auth/password-code', name: 'Password Code' },
  { id: '009', route: '/auth/new-password', name: 'Setup New Password' },
  { id: '010', route: '/auth/password-code', name: 'Maximum Attempts (Overlay)' },
  { id: '011', route: '/auth/new-password', name: 'Setup New Password (Alt)' },
  { id: '012', route: '/auth/password-code', name: 'Maximum Attempts (Overlay Alt)' },
  { id: '013', route: '/shop/categories-filter', name: 'All Categories' },
  { id: '014', route: '/search', name: 'Search' },
  { id: '015', route: '/onboarding/hello-card', name: 'Onboarding Hello' },
  { id: '016', route: '/onboarding/ready-card', name: 'Onboarding Ready' },
  { id: '017', route: '/shop/clothing', name: 'Shop Results' },
  { id: '018', route: '/flash-sale', name: 'Flash Sale' },
  { id: '019', route: '/(tabs)/home', name: 'Home' },
  { id: '020', route: '/(tabs)/account', name: 'Account' },
  { id: '052', route: '/payment/methods', name: 'Payment Method (1 Card)' },
  { id: '053', route: '/payment/methods', name: 'Payment Method (2 Cards)' },
  { id: '054', route: '/checkout', name: 'Payment In Progress (State)' },
  { id: '067', route: '/orders/review', name: 'Review Done (State)' },
  { id: '090', route: '/settings/payments', name: 'Add Card Sheet (Overlay)' },
  { id: '091', route: '/settings/payments', name: 'Edit Card Sheet (Overlay)' },
  { id: '100', route: '/settings', name: 'Delete Account Dialog (Popup)' },
] as const;
